version: '3.8'

services:
  web:
    build: .
    command: python main.py
    ports:
      - "8000:80"

    networks:
      - nep
    depends_on :
      - db  
    volumes:
      - .:/home/python
    


  db:
    image : mysql:latest
    volumes :
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "projetapi"
      MYSQL_ROOT_PASSWORD: "ghy"
      MYSQL_USER: "root"
    ports:
      - "3306:3306"
    networks:
      - nep

  networks:
    nep:
      driver: bridge


volumes:
  mysql_data:
    name: nep-mysql-data

  



