version: '3.8'

services:
  web:
    build: .
    command: python main.py
    ports:
      - "8000:80"
    depends_on :
      - db  
    volumes:
      - .:/home/python
    


  db:
    image : mysql:latest
    volumes :
      - mysql_data:/var/lib/mysql
    environment:
      DATABASE_HOST: "localhost"
      DATABASE_NAME: "projetapi"
      DATABASE_PASSWORD: "ghy"
      DATABASE_USER: "root"
    ports:
      - "3306:3306"


volumes:
  mysql_data:
    name: nep-mysql-data

  



