version: '3.8'
services:
  web:
    build: .
    command: python main.py
    ports:
      - "8000:80"
    depends_on :
      - db  
    volumes:
      - .:home/python


  db:
    image : mysql:latest
    volumes :
      - mysql_data/var/lib/mysql
    environment:
      DB_HOST: ""
      DB_PORT: ""
      DB_NAME: ""
      DB_PASSWORD: ""
      DB_USER: "nep"


volumes:
  mysql_data:
    name: nep-mysql-data


  



